// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3IUU5DQc9XXxPLoQ9ctt_o7AyYJZgds4',
    appId: '1:266026738752:android:eddfcbc4becb411e202ba5',
    messagingSenderId: '266026738752',
    projectId: 'attendanceapp-30b83',
    storageBucket: 'attendanceapp-30b83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkxghiry0qFq5HzXbM_j8FKqopL_UVbXc',
    appId: '1:266026738752:ios:47a7e6187169a042202ba5',
    messagingSenderId: '266026738752',
    projectId: 'attendanceapp-30b83',
    storageBucket: 'attendanceapp-30b83.firebasestorage.app',
    iosBundleId: 'com.igz.attendance',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeE3RFfKA7UfjqEZh1tKFzaHOSHD3AxOM',
    appId: '1:266026738752:web:2a48bb89e205d267202ba5',
    messagingSenderId: '266026738752',
    projectId: 'attendanceapp-30b83',
    authDomain: 'attendanceapp-30b83.firebaseapp.com',
    storageBucket: 'attendanceapp-30b83.appspot.com',
    measurementId: 'G-0KQD67GL5L',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwclF6jNc_dDc4v-IUTuSEw3ObsUpApY8',
    appId: '1:266026738752:web:2a6d88cddd018f1c202ba5',
    messagingSenderId: '266026738752',
    projectId: 'attendanceapp-30b83',
    authDomain: 'attendanceapp-30b83.firebaseapp.com',
    storageBucket: 'attendanceapp-30b83.firebasestorage.app',
    measurementId: 'G-5CB2CHKXGJ',
  );

}